version: 2.1
jobs:
  build:
    run_test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: Install npm dependencies
              command:
                npm install --save
            - run:
                name: Run Unit Test
                command:
                    ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results, reportFilename=test-results
            -store_test_results:
                path: test-results
            -store_artifacts:
                path: test-results
workflows:
    build_test:
        jobs:
          - run_tests